### ISSUE TITLE
Binscure Deobfuscator is Broken

### ISSUE THREAD

**Issue by Skidder1337** [narumii/Deobfuscator#23]
Method "<clinit>" in class a1Y has illegal signature "(Ljava/lang/Throwable;)V"

**Comment by narumii** [comment]
You can add **-noverify** to **JVM arguments** or at first run **SignatureRemoveTransformer** transformer

**Comment by Skidder1337** [comment]
then it drop 
Exception in thread "main" java.lang.NoClassDefFoundError: ac
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at uwu.narumi.deobfuscator.sandbox.SandBox.buildClass(SandBox.java:57)
	at uwu.narumi.deobfuscator.sandbox.SandBox.buildClasses(SandBox.java:48)
	at uwu.narumi.deobfuscator.sandbox.SandBox.put(SandBox.java:34)
	at uwu.narumi.deobfuscator.transformer.impl.binsecure.latest.BinsecureStringTransformer.transform(BinsecureStringTransformer.java:62)
	at uwu.narumi.deobfuscator.Deobfuscator.lambda$transform$1(Deobfuscator.java:112)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at uwu.narumi.deobfuscator.Deobfuscator.transform(Deobfuscator.java:107)
	at uwu.narumi.deobfuscator.transformer.ComposedTransformer.transform(ComposedTransformer.java:13)
	at uwu.narumi.deobfuscator.Deobfuscator.lambda$transform$1(Deobfuscator.java:112)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at uwu.narumi.deobfuscator.Deobfuscator.transform(Deobfuscator.java:107)
	at uwu.narumi.deobfuscator.Deobfuscator.start(Deobfuscator.java:67)
	at Loader.main(Loader.java:32)
Caused by: java.lang.ClassNotFoundException: ac
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at uwu.narumi.deobfuscator.sandbox.SandBox.findClass(SandBox.java:70)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 15 more

**Comment by Memexurer** [comment]
rat ewidentnie

**Comment by narumii** [comment]
Can i have sample jar?

**Comment by HeyaGlitz** [comment]
@Skidder1337 can this issue be closed?

**Comment by narumii** [comment]
it will be closed when i fix binsecure transformers

**Comment by HeyaGlitz** [comment]
okay, what about other issues?

**Comment by narumii** [comment]
who knows

**Comment by narumii** [comment]
v2 - closing
